package com.javaproject;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
@CrossOrigin(origins = "http://localhost:4200")
public class MainController {
	
	@Autowired
	// This means to get the bean called userRepository which is auto-generated by Spring
	private UserRepository userRepository;
	
	@Autowired
	private TypeRepository typeRepository;
	
	// Add User
	@PostMapping("/users")
	void addUser(@RequestBody User user) {
		userRepository.save(user);
	}
	
	// Retrieve users to print
	@GetMapping("/users")
	public @ResponseBody Iterable<User> getAllUser() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	
	// Add Type
	@PostMapping("/types")
	void addType(@RequestBody Type type) {
		typeRepository.save(type);
	}
	
	// Retrieve types to print
	@GetMapping("/types")
	public @ResponseBody Iterable<Type> getAllType() {
		// This returns a JSON or XML with the users
		return typeRepository.findAll();
	}
	
	// Delete User
	@DeleteMapping("/users/delete_user/{id}")
    public int delete_user(@PathVariable("id") int id) {
        userRepository.deleteById(id);
        return 1;
    }
	
	// Delete Type
	@DeleteMapping("/types/delete_type/{id}")
    public int delete_type(@PathVariable("id") int id) {
        typeRepository.deleteById(id);
        return 1;
    }
}
